from __future__ import annotations

from thesis_pkg.core.sec.filing_text import (
    ACC_HEADER_PATTERN,
    CIK_HEADER_PATTERN,
    CONTINUED_PATTERN,
    DATE_HEADER_PATTERN,
    EMPTY_ITEM_PATTERN,
    FILENAME_PATTERN,
    HEADER_SEARCH_LIMIT_DEFAULT,
    ITEM_CANDIDATE_PATTERN,
    ITEM_LINESTART_PATTERN,
    ITEM_WORD_PATTERN,
    PAGE_HYPHEN_PATTERN,
    PAGE_NUMBER_PATTERN,
    PAGE_OF_PATTERN,
    PAGE_ROMAN_PATTERN,
    PART_LINESTART_PATTERN,
    PART_MARKER_PATTERN,
    TOC_HEADER_LINE_PATTERN,
    TOC_MARKER_PATTERN,
    FilingItemSchema,
    ParsedFilingSchema,
    RawTextSchema,
    extract_filing_items,
    parse_filename_minimal,
    parse_header,
)
from thesis_pkg.io.parquet import PARQUET_MAGIC, concat_parquets_arrow
from thesis_pkg.pipelines.sec_pipeline import (
    build_light_metadata,
    build_light_metadata_dataset,
    compute_no_item_diagnostics,
    aggregate_no_item_stats_csvs,
    merge_parquet_files_arrow,
    merge_yearly_batches,
    process_year_dir_extract_items,
    process_year_dir_extract_non_items,
    process_year_parquet_extract_non_items,
    process_year_parquet_extract_items,
    process_zip_year,
    process_zip_year_raw_text,
    summarize_item_year_parquets,
    summarize_year_parquets,
)
